version: "3"

services: 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment: 
      - discovery.type=single-node
    networks: 
      - net

  logstash:
    build: ./logstash
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes: 
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    networks:
      - net
    environment:
      - LOG_LEVEL=fatal

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - net

  nginx:
    image: nginx:latest
    depends_on:
      - logstash
    ports:
      - 80:80
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

networks: 

  net:
    driver: bridge
